let carsData = [
  {
    id: 1,
    company: "Tata",
    model: "Nexon",
    price: 7.8,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41645/tata-nexon-right-front-three-quarter3.jpeg?q=75",
  },
  {
    id: 2,
    company: "Tata",
    model: "Punch",
    price: 8.45,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/39015/punch-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 3,
    company: "Tata",
    model: "Altroz",
    price: 6.6,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/32597/altroz-exterior-right-front-three-quarter-79.jpeg?isig=0&q=75",
  },
  {
    id: 4,
    company: "Tata",
    model: "Tiago",
    price: 5.6,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/39345/tiago-exterior-right-front-three-quarter-25.jpeg?isig=0&q=75",
  },
  {
    id: 5,
    company: "Tata",
    model: "Harrier",
    price: 15,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/142739/harrier-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 6,
    company: "Tata",
    model: "Safari",
    price: 25,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/142865/safari-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 7,
    company: "Tata",
    model: "Tiaogo NRG",
    price: 8,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/99113/tiago-nrg-bs6-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 8,
    company: "Tata",
    model: "Tigor",
    price: 8.9,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41160/tigor-exterior-right-front-three-quarter-3.png?isig=0&q=75",
  },
  {
    id: 9,
    company: "Maruthi Suziki",
    model: "Fronx",
    price: 13.14,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/130591/fronx-exterior-right-front-three-quarter-4.jpeg?isig=0&q=75",
  },
  {
    id: 10,
    company: "Maruthi Suziki",
    model: "Brezza",
    price: 14.14,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/107543/vitara-brezza-2022-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 11,
    company: "Maruthi Suziki",
    model: "Baleno",
    price: 9.88,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/102663/baleno-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 12,
    company: "Maruthi Suziki",
    model: "Grand Vitara",
    price: 19.9,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/123185/grand-vitara-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 13,
    company: "Maruthi Suziki",
    model: "Swift",
    price: 9.03,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75",
  },
  {
    id: 14,
    company: "Maruthi Suziki",
    model: "Ertiga",
    price: 13.08,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/115777/2022-ertiga-exterior-right-front-three-quarter-3.jpeg?isig=0&q=75",
  },
  {
    id: 15,
    company: "Maruthi Suzuki",
    model: "Alto K10",
    price: "5.96",
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/127563/new-alto-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 16,
    company: "Maruthi Suzuki",
    model: "Wagon R",
    price: 8.5,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/112947/wagon-r-2022-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 17,
    company: "Toyota",
    model: "Urban Cruiser Hyryder",
    price: 10.73,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/124027/urban-cruiser-hyryder-exterior-right-front-three-quarter-3.jpeg?isig=0&q=75",
  },
  {
    id: 18,
    company: "Toyota",
    model: "Innova Crysta",
    price: 25.43,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/140809/innova-crysta-exterior-right-front-three-quarter.png?isig=0&q=75",
  },
  {
    id: 19,
    company: "Toyota",
    model: "Fortuner",
    price: 50.34,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-19.jpeg?q=75",
  },
  {
    id: 20,
    company: "Toyota",
    model: "Glanza",
    price: 10,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/112839/glanza-facelift-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 21,
    company: "Toyota",
    model: "Innova Hycross",
    price: 29.99,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/115025/innova-hycross-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 22,
    company: "Toyota",
    model: "Fortuner Legender",
    price: 46.54,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/137767/fortuner-legender-exterior-right-front-three-quarter-4.png?isig=0&q=75",
  },
  {
    id: 23,
    company: "Toyota",
    model: "Land Cruiser",
    price: 2.1,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/139739/land-cruiser-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 24,
    company: "Toyota",
    model: "Vellfire",
    price: 96.44,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41217/toyota-vellfire-right-front-three-quarter5.jpeg?q=75",
  },
  {
    id: 25,
    company: "Hyundai",
    model: "Grand i10",
    price: 5.73,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/136183/grand-i10-nios-facelift-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  },
  {
    id: 26,
    company: "Hyundai",
    model: "Creta",
    price: 19.2,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/141115/creta-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 27,
    company: "Hyundai",
    model: "Venue",
    price: 13.18,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/141113/venue-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 28,
    company: "Hyundai",
    model: "i20",
    price: 11.83,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/40530/i20-exterior-right-front-three-quarter-5.jpeg?q=75",
  },
  {
    id: 29,
    company: "Hyundai",
    model: "Verna",
    price: 17.38,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/121943/verna-facelift-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 30,
    company: "Hyundai",
    model: "Aura",
    price: 8.9,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/139133/aura-2023-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 31,
    company: "Hyundai",
    model: "Alcazar",
    price: 21.13,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/142523/alcazar-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 32,
    company: "Hyundai",
    model: "Tucson",
    price: 35.64,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/106821/new-tucson-exterior-right-front-three-quarter-5.jpeg?isig=0&q=75",
  },
  {
    id: 33,
    company: "Mahindra",
    model: "Thar",
    price: 10.55,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/40087/thar-exterior-right-front-three-quarter-11.jpeg?q=75",
  },
  {
    id: 34,
    company: "Mahindra",
    model: "Scorpio",
    price: 13,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/128413/scorpio-exterior-right-front-three-quarter-46.jpeg?isig=0&q=75",
  },
  {
    id: 35,
    company: "Mahindra",
    model: "Scorpio N",
    price: 24.52,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-15.jpeg?isig=0&q=75",
  },
  {
    id: 36,
    company: "Mahindra",
    model: "XUV 700",
    price: 26.18,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 37,
    company: "Mahindra",
    model: "XUV 300",
    price: 8.41,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/26918/xuv300-exterior-right-front-three-quarter-148706.jpeg?q=75",
  },
  {
    id: 38,
    company: "Mahindra",
    model: "Bolero",
    price: 10.79,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/131179/bolero-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 39,
    company: "Mahindra",
    model: "Bolero Neo",
    price: 9.63,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/131181/bolero-neo-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  },
  {
    id: 40,
    company: "Mahindra",
    model: "XUV 400",
    price: 15.99,
    img: "https://imgd.aeplcdn.com/664x374/n/cw/ec/45278/xuv400-exterior-right-front-three-quarter-4.jpeg?isig=0&q=75",
  },
];
